spring.application.name=validation-service
spring.datasource.url=jdbc:postgresql://localhost:5432/validation_db
spring.datasource.username=validation_user
spring.datasource.password=1234567
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
