spring.application.name=monolithic

spring.datasource.url=jdbc:postgresql://localhost:5432/monolithic
spring.datasource.username=monolithicuser
spring.datasource.password=12345678

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update